In [12]:
import numpy as np

In [13]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],
    [17,18,19,20]
]) 

In [14]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [15]:
x.shape

(5, 4)

In [18]:
x[:, 0]

array([ 1,  5,  9, 13, 17])

In [19]:
x[2, 0]

9

In [21]:
x[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [26]:
x[1::2, 1::2] = 999

In [27]:
x

array([[  1,   2,   3,   4],
       [  5, 999,   7, 999],
       [  9,  10,  11,  12],
       [ 13, 999,  15, 999],
       [ 17,  18,  19,  20]])

In [40]:
x = np.array([
    [
        [1, 1.1, 1.2],
        [2, 2.1, 2.2],
        [3, 3.1, 3.2]
    ], 
    [
        [4, 4.1, 4.2],
        [5, 5.1, 5.2],
        [6, 6.1, 6.2]
    ]
])

In [41]:
x

array([[[1. , 1.1, 1.2],
        [2. , 2.1, 2.2],
        [3. , 3.1, 3.2]],

       [[4. , 4.1, 4.2],
        [5. , 5.1, 5.2],
        [6. , 6.1, 6.2]]])

In [42]:
x.shape

(2, 3, 3)

IndexError: an index can only have a single ellipsis ('...')